version: '3.9'
services:
  db:
    image: postgres:15
    container_name: devapi_db
    restart: always
    environment:
      POSTGRES_USER: devapi
      POSTGRES_PASSWORD: devapi123
      POSTGRES_DB: devapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: